[package]
name = "simple_server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
sys-info = "0.9"
serde = { version = "1.0", features = ["derive"] }
if-addrs = "0.10"
pnet = "0.34"
default-net = "0.21"
